# My variables
name: City Island Lobster House
description: City Island Lobster House
google_verification: null
future: true
encoding: UTF-8

baseurl: "http://cilobsterhouse.com" # the subpath of your site, e.g. /blog
url: "cilobsterhouse.com" # the base hostname & protocol for your site


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
